CREATE TABLE tienda (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nombre" varchar(255) NOT NULL,
  CONSTRAINT "almacen_pk" PRIMARY KEY ("tienda_id")
)
;

CREATE TABLE producto (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "imgSrc" varchar(255),
  "dataOriginal" varchar(255),
  "imgTitle" varchar(255) NOT NULL,
  "priceDolar" varchar(100) NOT NULL,
  "priceSoles" varchar(100) NOT NULL,
  "url" varchar(100) NOT NULL,
  "tienda_id" int4 NOT NULL,
  CONSTRAINT "producto_pk" PRIMARY KEY ("id")
)
;


ALTER TABLE producto ADD CONSTRAINT "fk_producto_tienda" FOREIGN KEY ("tienda_id") REFERENCES tienda ("id");


INSERT INTO producto("imgSrc", "dataOriginal", "imgTitle", "priceDolar", "priceSoles", url, tienda_id)
	VALUES ('prueba', 'prueba', 'prueba', 'prueba', 'prueba', 'prueba', 1);
INSERT INTO tienda (nombre) VALUES('Importaciones Impacto');
INSERT INTO tienda (nombre) VALUES('C&C Computer');
INSERT INTO tienda (nombre) VALUES(' Corporación Sercoplus SAC.');

select * from tienda
select * from producto
